language: java

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m -Xms256m"
    - JAVA_OPTS="-Xmx256m -Xms256m"

install: true

before_script:
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-all-3.5.1.tar.gz
  - tar -xzvf protobuf-all-3.5.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd

script:
  - ./mvnw --projects bdse-kvnode clean package
  - ./mvnw --projects bdse-integration-tests --also-make test