language: java

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m -Xms256m"
    - JAVA_OPTS="-Xmx256m -Xms256m"

install: true

before_script:
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - unzip protoc-3.5.1-linux-x86_64.zip
  - cp ./bin/protoc /usr/bin/

script:
  - ./mvnw package
