language: java

sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - MAVEN_OPTS="-Xmx256m -Xms256m"
    - JAVA_OPTS="-Xmx256m -Xms256m"

install: true

script:
  - ./mvnw --projects bdse-kvnode clean package
  - ./mvnw --projects bdse-integration-tests --also-make test